const Anthropic = require('@anthropic-ai/sdk');
const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, LevelFormat } = require('docx');
const pool = require('../../../db/index');
const { createNotification } = require('../services/notificationService');

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

async function generatePlan(req, res) {
  const { startupDescription, workspaceId } = req.body;

  if (!startupDescription) {
    return res.status(400).json({ error: 'startupDescription is required' });
  }

  try {
    const message = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 4096,
      system: 'You are a startup launch planning assistant. You return only valid JSON. No markdown, no explanation, no code fences. Only a raw JSON object.',
      messages: [
        {
          role: 'user',
          content: `Generate a launch plan for the following startup: ${startupDescription}. Return a JSON object with this exact structure: { "projects": [ { "name": "string", "description": "string", "tasks": [ { "title": "string", "description": "string", "priority": "high" | "medium" | "low" } ] } ] }. Include 3 to 5 projects. Each project should have 3 to 6 tasks. Make the projects and tasks specific and actionable for this startup.`,
        },
      ],
    });

    const text = message.content[0].text;

    let plan;
    try {
      plan = JSON.parse(text);
    } catch {
      return res.status(500).json({ error: 'AI returned invalid JSON' });
    }

    return res.status(200).json(plan);
  } catch (err) {
    console.error('generatePlan error:', err.message);
    return res.status(500).json({ error: 'Failed to generate plan' });
  }
}

// projects table columns: id, user_id, name, description, status, created_at, updated_at
// tasks table columns: id, project_id, user_id, title, description, status, due_date, created_at, updated_at, priority
async function savePlan(req, res) {
  const { workspaceId, projects } = req.body;

  if (!workspaceId || !Array.isArray(projects) || projects.length === 0) {
    return res.status(400).json({ error: 'workspaceId and projects array are required' });
  }

  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    let taskCount = 0;
    const insertedProjects = [];

    for (const project of projects) {
      const projectResult = await client.query(
        'INSERT INTO projects (user_id, name, description, status) VALUES ($1, $2, $3, $4) RETURNING id',
        [req.user.id, project.name, project.description || null, 'active']
      );
      const projectId = projectResult.rows[0].id;
      insertedProjects.push({ id: projectId, name: project.name, description: project.description || '' });

      for (const task of project.tasks || []) {
        await client.query(
          'INSERT INTO tasks (project_id, user_id, title, description, priority, status) VALUES ($1, $2, $3, $4, $5, $6)',
          [projectId, task.userId || req.user.id, task.title, task.description || null, task.priority || 'medium', 'open']
        );
        taskCount++;
      }
    }

    await client.query('COMMIT');

    await createNotification(
      req.user.id,
      'plan_generated',
      `Your AI launch plan has been saved with ${insertedProjects.length} projects and ${taskCount} tasks.`
    );

    return res.status(201).json({
      message: 'Plan saved successfully',
      projectCount: insertedProjects.length,
      taskCount,
      projects: insertedProjects,
    });
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('savePlan error:', err.message);
    return res.status(500).json({ error: 'Failed to save plan' });
  } finally {
    client.release();
  }
}

async function generatePlanDoc(req, res) {
  const { plan } = req.body;

  if (!plan || !Array.isArray(plan.projects)) {
    return res.status(400).json({ error: 'plan with projects array is required' });
  }

  const children = [
    new Paragraph({
      text: 'LaunchForge AI — Launch Plan',
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.LEFT,
      spacing: { after: 100 },
      run: { font: 'Arial' },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Generated by LaunchForge AI', italics: true, font: 'Arial', size: 22 }),
      ],
      spacing: { after: 200 },
    }),
    new Paragraph({ text: '', spacing: { after: 200 } }),
  ];

  for (const project of plan.projects) {
    children.push(
      new Paragraph({
        text: project.name,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 100 },
        run: { font: 'Arial' },
      })
    );
    children.push(
      new Paragraph({
        children: [new TextRun({ text: project.description || '', font: 'Arial', size: 22 })],
        spacing: { after: 150 },
      })
    );
    children.push(
      new Paragraph({
        children: [new TextRun({ text: 'Tasks:', bold: true, font: 'Arial', size: 22 })],
        spacing: { after: 100 },
      })
    );

    for (const task of project.tasks || []) {
      const label = (task.priority || 'medium').toUpperCase();
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `[${label}] ${task.title}`, bold: true, font: 'Arial', size: 22 }),
            new TextRun({ text: ` — ${task.description || ''}`, font: 'Arial', size: 22 }),
          ],
          numbering: { reference: 'bullet-list', level: 0 },
          spacing: { after: 80 },
        })
      );
    }
  }

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: 'bullet-list',
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: '•',
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children,
      },
    ],
  });

  try {
    const buffer = await Packer.toBuffer(doc);
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', 'attachment; filename="LaunchForge-Plan.docx"');
    return res.send(buffer);
  } catch (err) {
    console.error('generatePlanDoc error:', err.message);
    return res.status(500).json({ error: 'Failed to generate document' });
  }
}

async function generateCampaigns(req, res) {
  const { projects } = req.body;

  if (!Array.isArray(projects) || projects.length === 0) {
    return res.status(400).json({ error: 'projects array is required' });
  }

  try {
    const results = await Promise.all(
      projects.map(async (project) => {
        const message = await client.messages.create({
          model: 'claude-opus-4-5',
          max_tokens: 2048,
          system: 'You are a startup marketing expert. You return only valid JSON. No markdown, no explanation, no code fences.',
          messages: [
            {
              role: 'user',
              content: `Generate a marketing campaign for a startup project called '${project.name}'. Project description: '${project.description}'. Return a JSON object with this exact structure: { "campaign_type": "launch_email" | "social_media" | "ad_creative", "content": "the full campaign content as a string" }`,
            },
          ],
        });

        const parsed = JSON.parse(message.content[0].text);

        await pool.query(
          'INSERT INTO campaigns (workspace_id, project_id, campaign_type, content, status, generated_by_ai) VALUES ($1, $2, $3, $4, $5, $6)',
          [1, project.id, parsed.campaign_type, parsed.content, 'draft', true]
        );

        return {
          project_id: project.id,
          campaign_type: parsed.campaign_type,
          content: parsed.content,
        };
      })
    );

    await createNotification(
      req.user.id,
      'campaign',
      `AI generated ${results.length} campaign(s) from your launch plan.`
    );

    return res.status(201).json({ message: 'Campaigns generated', campaigns: results });
  } catch (err) {
    console.error('generateCampaigns error:', err.message);
    return res.status(500).json({ error: 'Failed to generate campaigns' });
  }
}

module.exports = { generatePlan, savePlan, generatePlanDoc, generateCampaigns };
